// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	blog "blog/api/api/internal/handler/blog"
	"blog/api/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建评论
				Method:  http.MethodPost,
				Path:    "/comment",
				Handler: blog.CreateCommentHandler(serverCtx),
			},
			{
				// 获取评论列表
				Method:  http.MethodGet,
				Path:    "/comment/:postId",
				Handler: blog.GetCommentsHandler(serverCtx),
			},
			{
				// 创建文章
				Method:  http.MethodPost,
				Path:    "/post",
				Handler: blog.CreatePostHandler(serverCtx),
			},
			{
				// 获取文章列表
				Method:  http.MethodGet,
				Path:    "/post",
				Handler: blog.GetPostsHandler(serverCtx),
			},
			{
				// 获取文章详情
				Method:  http.MethodGet,
				Path:    "/post/:id",
				Handler: blog.GetPostHandler(serverCtx),
			},
			{
				// 更新文章
				Method:  http.MethodPut,
				Path:    "/post/:id",
				Handler: blog.UpdatePostHandler(serverCtx),
			},
			{
				// 删除文章
				Method:  http.MethodDelete,
				Path:    "/post/:id",
				Handler: blog.DeletePostHandler(serverCtx),
			},
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: blog.UserLoginHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: blog.UserRegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
