// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type CreatePostReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	UserId  string `json:"user_id"`
}

type CreatePostResp struct {
	Id int64 `json:"id"`
}

type DeletePostReq struct {
	Id int64 `path:"id"`
}

type DeletePostResp struct {
	Success bool `json:"success"`
}

type GetPostReq struct {
	Id int64 `path:"id"`
}

type GetPostResp struct {
	Id        int64  `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	UserId    int64  `json:"userId"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type GetPostsReq struct {
	Page  int `form:"page"`
	Limit int `form:"limit"`
}

type GetPostsResp struct {
	Posts []Post `json:"posts"`
}

type UpdatePostReq struct {
	Id      int64  `path:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type UpdatePostResp struct {
	Success bool `json:"success"`
}
