// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type UserLoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	Token string `json:"token"`
}

type UserRegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type UserRegisterResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}
