// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	comment "test2/internal/handler/comment"
	post "test2/internal/handler/post"
	user "test2/internal/handler/user"
	"test2/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建评论
				Method:  http.MethodPost,
				Path:    "/comment/Create",
				Handler: comment.CreateCommentHandler(serverCtx),
			},
			{
				// 获取评论列表
				Method:  http.MethodGet,
				Path:    "/comment/info",
				Handler: comment.GetCommentsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建文章
				Method:  http.MethodPost,
				Path:    "/post/Create",
				Handler: post.CreatePostHandler(serverCtx),
			},
			{
				// 删除文章
				Method:  http.MethodDelete,
				Path:    "/post/delete",
				Handler: post.DeletePostHandler(serverCtx),
			},
			{
				// 获取文章详情
				Method:  http.MethodGet,
				Path:    "/post/info",
				Handler: post.GetPostHandler(serverCtx),
			},
			{
				// 获取文章列表
				Method:  http.MethodGet,
				Path:    "/post/list",
				Handler: post.GetPostsHandler(serverCtx),
			},
			{
				// 更新文章
				Method:  http.MethodPut,
				Path:    "/post/update",
				Handler: post.UpdatePostHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.UserLoginHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.UserRegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
