// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type CreateCommentReq struct {
	PostId  int64  `json:"postId"`
	Content string `json:"content"`
}

type CreateCommentResp struct {
	Id int64 `json:"id"`
}

type GetCommentsReq struct {
	PostId int64 `path:"postId"`
}

type GetCommentsResp struct {
	Comments []Comment `json:"comments"`
}
