// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type Comment struct {
	Id        int64  `json:"id"`
	Content   string `json:"content"`
	UserId    int64  `json:"userId"`
	PostId    int64  `json:"postId"`
	CreatedAt string `json:"createdAt"`
}

type Post struct {
	Id        int64  `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	UserId    int64  `json:"userId"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
