// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	postsFieldNames          = builder.RawFieldNames(&Posts{})
	postsRows                = strings.Join(postsFieldNames, ",")
	postsRowsExpectAutoSet   = strings.Join(stringx.Remove(postsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	postsRowsWithPlaceHolder = strings.Join(stringx.Remove(postsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheZeroDemoPostsIdPrefix = "cache:zeroDemo:posts:id:"
)

type (
	postsModel interface {
		Insert(ctx context.Context, data *Posts) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Posts, error)
		Update(ctx context.Context, data *Posts) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPostsModel struct {
		sqlc.CachedConn
		table string
	}

	Posts struct {
		Id        int64     `db:"id"`
		Title     string    `db:"title"`
		Content   string    `db:"content"`
		UserId    int64     `db:"user_id"`
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newPostsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPostsModel {
	return &defaultPostsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`posts`",
	}
}

func (m *defaultPostsModel) Delete(ctx context.Context, id int64) error {
	zeroDemoPostsIdKey := fmt.Sprintf("%s%v", cacheZeroDemoPostsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, zeroDemoPostsIdKey)
	return err
}

func (m *defaultPostsModel) FindOne(ctx context.Context, id int64) (*Posts, error) {
	zeroDemoPostsIdKey := fmt.Sprintf("%s%v", cacheZeroDemoPostsIdPrefix, id)
	var resp Posts
	err := m.QueryRowCtx(ctx, &resp, zeroDemoPostsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", postsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostsModel) Insert(ctx context.Context, data *Posts) (sql.Result, error) {
	zeroDemoPostsIdKey := fmt.Sprintf("%s%v", cacheZeroDemoPostsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, postsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Title, data.Content, data.UserId)
	}, zeroDemoPostsIdKey)
	return ret, err
}

func (m *defaultPostsModel) Update(ctx context.Context, data *Posts) error {
	zeroDemoPostsIdKey := fmt.Sprintf("%s%v", cacheZeroDemoPostsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, postsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Title, data.Content, data.UserId, data.Id)
	}, zeroDemoPostsIdKey)
	return err
}

func (m *defaultPostsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheZeroDemoPostsIdPrefix, primary)
}

func (m *defaultPostsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", postsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPostsModel) tableName() string {
	return m.table
}
