// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type Comment struct {
	Id        int64  `json:"id"`
	Content   string `json:"content"`
	UserId    int64  `json:"userId"`
	PostId    int64  `json:"postId"`
	CreatedAt string `json:"createdAt"`
}

type CreateCommentReq struct {
	PostId  int64  `json:"postId"`
	Content string `json:"content"`
}

type CreateCommentResp struct {
	Id int64 `json:"id"`
}

type CreatePostReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type CreatePostResp struct {
	Id int64 `json:"id"`
}

type DeletePostReq struct {
	Id int64 `path:"id"`
}

type DeletePostResp struct {
	Success bool `json:"success"`
}

type GetCommentsReq struct {
	PostId int64 `path:"postId"`
}

type GetCommentsResp struct {
	Comments []Comment `json:"comments"`
}

type GetPostReq struct {
	Id int64 `path:"id"`
}

type GetPostResp struct {
	Id        int64  `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	UserId    int64  `json:"userId"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type GetPostsReq struct {
	Page  int `form:"page"`
	Limit int `form:"limit"`
}

type GetPostsResp struct {
	Posts []Post `json:"posts"`
}

type Post struct {
	Id        int64  `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	UserId    int64  `json:"userId"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type UpdatePostReq struct {
	Id      int64  `path:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type UpdatePostResp struct {
	Success bool `json:"success"`
}

type UserLoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	Token string `json:"token"`
}

type UserRegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type UserRegisterResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}
